plugins:
  localfs:
    config:
      local_dir: /Users/mac/.openclaw/workspace/openviking_data/viking
    enabled: true
    path: /local
  queuefs:
    enabled: true
    path: /queue
  serverinfofs:
    config:
      version: 1.0.0
    enabled: true
    path: /serverinfo
server:
  address: :1833
  log_level: warn
